### ISSUE TITLE
Bug: IOException error / Blank window display

### ISSUE THREAD

**Issue by Ratmaniak** [grocy/grocy-desktop#38]
Having some peculiar errors in Grocy-desktop, but I'm not adept enough to tell if it's something I've borked in the install, or an issue to be raised. It _had_ been working fine for a few days, linking with the android companion app nicely. 

Trying to examine the Inventory or Stock Overview, I get the following error: 

> The process cannot access the file 'C:\Grocy\grocy-data.zip' because it is being used by another process.

>    Exception Stacktrace

>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
>    at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
>    at GrocyDesktop.FrmMain.UserDataSyncSave()
>    at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
>    at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
>    at System.Windows.Forms.Application.ExitInternal()
>    at System.Windows.Forms.Application.Restart()
>    at GrocyDesktop.FrmMain.ToolStripMenuItem_EnableExternalAccess_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The basic interface also comes up blank most of the time, with no clear workaround to make it come back - inventory / products / main display window is consistently blank.
Using debug console shows several critical errors.

[192.168.10.47-1646572064410.log](https://github.com/grocy/grocy-desktop/files/8192623/192.168.10.47-1646572064410.log)

Any advice?

**Comment by berrnd** [comment]
> The process cannot access the file 'C:\Grocy\grocy-data.zip' because it is being used by another process.

Most probably you tried to restore a backup or use ["User data synchronization"](https://github.com/grocy/grocy-desktop), otherwise grocy-desktop never tries to read a "data ZIP file".

So simply double check that this file is readable and not used by another process, as the error message implies. Also often fancy anti-malware tools conflict with software like grocy-desktop. I would recommend to add proper exception, also makes things faster most of the time.

> Using debug console shows several critical errors.

When grocy-desktop has problems running and the webserver also doesn't seem to run properly, errors in the JS console are not so uncommon - most of them are just resource fetching errors.

Beside that, this is the place for reproducible bugs, not for general help as [mentioned in README](https://github.com/grocy/grocy-desktop#questions--help--bug-reports--feature-requests).
