### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by kreisklasse** [grocy/grocy-desktop#5]
I installed _grocy-desktop_1.4.2.msi_ on **Windows 10 Home (Version1809)**

But on startup it shows following error two times, then empty grocy screen stys open:

![grocyerror](https://user-images.githubusercontent.com/25295915/56764565-4ff17600-67a5-11e9-8506-17c507e52ea8.png)

Restart of _grocy-desktop_1.4.2.msi_  and using "Repair" does not solve problem.

Remove and Re-Install does not solve the problem.

**Comment by kreisklasse** [comment]
Install via Microsoft Store gives the same error as above. :-(

**Comment by berrnd** [comment]
Sorry, was probably due to the change that the C++ Runtime is now included in the installer (was a requirement for Microsoft Store submission) - I was not aware that not only CefSharp, but also PHP has this dependency...

You can fix it in the meantime by installing the corresponding runtime on your machine, that one: https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe

**Comment by kreisklasse** [comment]
With pre-installing _vc_redist.x86.exe_ and then installing _grocy-desktop_1.4.2.msi_ solved the problem.
Grocy starts up now as it should.
