### ISSUE TITLE
Cross platform edition

### ISSUE THREAD

**Issue by CodingSpiderFox** [grocy/grocy-desktop#7]
Does the app also run on Linux?

If not, is support for Linux planned for the future?

**Comment by berrnd** [comment]
Currently it's Windows only - and I think it's also not possible, would need a whole different approach - as Windows Forms and CefSharp only supports Windows...

**Comment by CodingSpiderFox** [comment]
ok

**Comment by rugk** [comment]
One way would be the way all apps do nowadays… build an Electron version? (Given you already have a web interface and I guess this app is the same hmm…)

**Comment by berrnd** [comment]
> One way would be the way all apps do nowadays… build an Electron version? 

Right, because everyone uses that (personally currently using not a single Electron based app, but ok) you really think that fits each and every use case? Cool, just build an Electron app doing exactly everything Grocy Desktop does (auto-managing a web server, the PHP Runtime and everything else needed to run Grocy "embedded" on a client) + doing that cross platform - looking forward to that.

I'd be glad if you could spare the expert advices unless you really have a clue about the technical circumstances required exactly for this (Grocy) - throwing random "everyone uses `<buzzword>`, so simply use that" phrases in is nothing else than awkward, sorry to say how it is.

**Comment by rugk** [comment]
No reason to be passive aggressive like that. Actually yes it would be possible. The trickiest thing may be the webserver, but well given it is all NodeJS that is likely possible: https://www.fabiofranchino.com/blog/use-electron-as-local-webserver/
Even PHP is possible: https://github.com/aj-techsoul/ELECTRON-4-PHP

I am posting it to collect ideas with the help of the community that can work on every technical aspect. This is no attack towards your work or software, so no need to feel attacked here. Thus I ask you to also refrain from attacks against me, thanks.

Also what you personally use or not use is your personal matter. I am personally also somewhat critical against electron apps. That said, it is just a fact that many apps doing and wanting cross-plattform compatibility use Electron for that nowadays. So it fits this issue very well.

**Comment by berrnd** [comment]
Correct, everything doesn't matter (and you don't need to love me or Grocy). Simply build it instead of giving wise advice (still only partly technical relevant for the target use case of this project, I highly recommend looking a little bit more into the corresponding project before doing that - obviously you haven't done that so far and it also still looks to me you don't have the expertise related to what's needed at all - which is fine, but I'm pretty capable of googling "how to do x" myself). Building something says just more than being the wise man trying to educate people.
